spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/echo?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: tjfgmlrhks9478@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1770000
    jpa:
      hibernate:
        ddl-auto: update
        show_sql: true
        default_batch_fetch_size: 100
      properties:
        hibernate:
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc: debug