spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1770000

  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true

firebase:
  sdk:
    path: serviceAccountKey.json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc: debug