package woozlabs.echo.domain.gmail.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import woozlabs.echo.domain.calendar.dto.UnAvailableDatesResponse;
import woozlabs.echo.domain.calendar.service.CalendarService;
import woozlabs.echo.domain.chatGPT.service.ChatGptService;
import woozlabs.echo.domain.gmail.dto.draft.GmailDraftCommonRequest;
import woozlabs.echo.domain.gmail.dto.extract.GenScheduleEmailTemplateResponse;
import woozlabs.echo.global.exception.CustomErrorException;
import woozlabs.echo.global.exception.ErrorCode;

import java.util.List;

@Service
@Slf4j
@RequiredArgsConstructor
public class GenService {
    private final ObjectMapper om;
    private final ChatGptService chatGptService;
    private final CalendarService calendarService;
    private final AsyncGmailService ayncGmailService;

    public void generateScheduleEmailTemplate(String uid, String decodedContent, String toEmail){
        try{
            UnAvailableDatesResponse unAvailableDatesResponse = calendarService.getDatesWithNoEventsInTwoWeeks(uid);
            List<String> unAvailableDates = unAvailableDatesResponse.getUnavailableDates();
            String result = chatGptService.generateScheduleEmailTemplate(decodedContent, unAvailableDates);
            GenScheduleEmailTemplateResponse templateResponse = om.readValue(result, GenScheduleEmailTemplateResponse.class); // om 에러 한번씩 발생 해결 필요
            // create draft
            GmailDraftCommonRequest request = new GmailDraftCommonRequest();
            request.setSubject("Template automatically generated by Echo");
            request.setToEmailAddress(toEmail);
            request.setBodyText(templateResponse.getTemplate());
            ayncGmailService.createDraftForReplyTemplate(uid, request);
        }catch (Exception e) {
            throw new CustomErrorException(ErrorCode.GENERATE_SCHEDULE_EMAIL_TEMPLATE_ERROR, ErrorCode.GENERATE_SCHEDULE_EMAIL_TEMPLATE_ERROR.getMessage());
        }
    }
}
